[versions]
kotlin = "1.6.21"
coroutines = "1.6.1"
mockk = "1.12.4"
kotest = "5.3.0"
ktlint = "0.45.2"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.3.0" }