[versions]
ksp = "2.1.21-2.0.1"
appcompat = "1.7.1"
koin = "4.0.4"
koin-annotations = "2.0.0"
koin-android = "4.0.4"
koin-compose = "4.0.4"
kotlin = "2.1.21"
coroutines = "1.9.0"
kotest = "6.0.7"
material = "1.8.2"
mvi = "1.8.5"
activity = "1.10.1"
androidx-lifecycle = "2.8.4"
ktlint-gradle = "12.3.0"
android-library = "8.10.1"
maven-publish = "0.35.0"
ui = "1.8.2"

# its beeing used outside this file
ktlint-lib = "1.2.1"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotestRunner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mvi = { module = "com.adidas.mvi:mvi", version.ref = "mvi" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
material = { module = "androidx.compose.material:material", version.ref = "material" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koinAnnotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koinKspCompiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
koinCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
android-library = { id = "com.android.library", version.ref = "android-library" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotestMultiplatform = { id = "io.kotest", version.ref = "kotest" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version = "0.25.0" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


